export const KeychainKeys = {
  username: 'username',
  profilePicture: 'profilePicture',
  location: 'location',
  entropy: 'entropy',
  'wallet-zone-0-0': 'wallet-zone-0-0',
  'wallet-zone-0-1': 'wallet-zone-0-1',
  'wallet-zone-0-2': 'wallet-zone-0-2',
  'wallet-zone-1-0': 'wallet-zone-1-0',
  'wallet-zone-1-1': 'wallet-zone-1-1',
  'wallet-zone-1-2': 'wallet-zone-1-2',
  'wallet-zone-2-0': 'wallet-zone-2-0',
  'wallet-zone-2-1': 'wallet-zone-2-1',
  'wallet-zone-2-2': 'wallet-zone-2-2',
  contacts: 'contacts',
};
