import { SendScanScreenStrings } from './SendScanScreen/SendScanScreen.strings';
import { SendAmountScreenStrings } from './SendAmount/SendAmountScreen.strings';

export const send = {
  label: 'Send',
  amount: 'Amount',
  address: 'Address',
  tip: 'Tip',
  noTip: 'No tip',
  includeTip: 'Include a Tip?',
  includedTip: 'Included Tip',
  customTip: 'Custom tip',
  tipPlaceholder: 'Enter a tip amount',
  viewOnExplorer: 'View Transaction on QuaiSnap.com',
  pay: 'Pay',
  sending: 'Sending',
  gasFee: 'Gas Fee',
  totalCost: 'Total Cost',
  paymentConfirmed: 'Payment Confirmed!',
  paymentFailed: 'Transaction Failed.',
  paymentPending: 'Transaction Pending...',
  retry: 'Retry',
  saveToContacts: 'Save Recipient to Contacts',
  savedToContacts: 'Saved to Contacts',
  alreadySavedToContacts: 'Already Saved to Contacts',
  complete: 'Complete',
  somethingWrong: 'Something went wrong.',
  retryTransaction: 'Please retry the transaction.',
  noInternet: 'No Internet Connection',
  noInternetMessage: 'Please check your internet connection',
  SendScanScreen: SendScanScreenStrings,
  SendAmountScreen: SendAmountScreenStrings,
};
